<title> Python Basic Exercise #1 </title>

<img src="/logo_full.png" width="" align="" />

<br>

---

<br>

# Pandas Basic Exercise #3

Total Question: 11 Task
Topic: Basic, Grouping, Sorting

In [2]:
%pip install seaborn matplotlib scikit-learn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from seaborn) (3.0.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tzdata in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\MIka\Documents\Purwhadika\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   --------------------- ------------------ 4.5/8.3 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 22.4 MB/s  0:00:00
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------------- -------------- 5.2/8.1 MB 26.1 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 21.2 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 18.5 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   --------------------- ------------------ 3.9/7.2 MB 21.5 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 18.4 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   --- ------------------------------------ 3.7/37.3 MB 18.1 MB/s eta 0:00:02
   -------- ------------------------------- 8.4/37.3 MB 20.3 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 20.3 MB/s eta 0:00:02
   ---------------- ----------------------- 15.2/37.3 MB 17.9 MB/s eta 0:00:02
   ------------------- -------------------- 18.4/37.3 MB 17.4 MB/s eta 0:00:02
   ---------------------- ----------------- 21.2/37.3 MB 17.0 MB/s eta 0:00:01
   -------------------------- ------------- 24.9/37.3 MB 16.7 MB/s eta 0:00:01
   ------------------------------ --------- 28.3/37.3 MB 16.6 MB/s eta 0:00:01
   --------------------------------- ------ 31.5/37.3 MB 16.4 MB/s eta 0:00:01
   ------------------------------------- -- 34.9/37.3 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 16.0 MB/s  0:00:02
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, pyparsing, pillow, kiwisolver, joblib, fonttools, cycler, contourpy, scikit-learn, matplotlib, seaborn

   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   --- ------------------------------------  1/12 [scipy]
   ------ ---------------------------------  2/12 [pyparsing]
   ------ ---------------------------------  2/12 [pyparsing]
   ------ ---------------------------------  2/12 [pyparsing]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------- -----------------------------  3/12 [pillow]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   ---------------- -----------------------  5/12 [joblib]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   -------------------- -------------------  6/12 [fonttools]
   ----------------------- ----------------  7/12 [cycler]
   -------------------------- -------------  8/12 [contourpy]
   -------------------------- -------------  8/12 [contourpy]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]
   ------------------------------ ---------  9/12 [scikit-learn]

WARNING: Cache entry deserialization failed, entry ignored

In [3]:
import pandas as pd
import seaborn as sns

In [4]:
df = sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

## Task 1 - Tampilkan nilai yang paling sering muncul pada kolom 'origin'

In [81]:
# Your code here
display(df["origin"].mode()[0])
display(df["origin"].count())

'usa'

np.int64(398)

<br>

## Task 2 - Tampilkan rata-rata horsepower

In [82]:
# Your code here
df["horsepower"].mean().round(2)

np.float64(104.47)

<br>

## Task 3 - Tampilkan rata-rata acceleration tiap cylinder

In [ ]:
#Your code here
df.groupby("cylinders")["acceleration"].mean()

cylinders
3    13.250000
4    16.601471
5    18.633333
6    16.263095
8    12.955340
Name: acceleration, dtype: float64

<br>

## Task 4 - Tampilkan rata-rata acceleration tiap cylinder dan origin

In [19]:
# Your code here
df.groupby(["cylinders", "origin"])["acceleration"].mean()

cylinders  origin
3          japan     13.250000
4          europe    16.722222
           japan     16.569565
           usa       16.526389
5          europe    18.633333
6          europe    16.425000
           japan     13.550000
           usa       16.474324
8          usa       12.955340
Name: acceleration, dtype: float64

<br>

## Task 5 - Tampilkan rata-rata acceleration tiap cylinder dan origin, kemudian urutkan hasilnya dari acceleration paling tinggi.

In [36]:
# Your code here
df.groupby(["cylinders", "origin"])["acceleration"].mean().sort_values(ascending=False, inplace=False)

cylinders  origin
5          europe    18.633333
4          europe    16.722222
           japan     16.569565
           usa       16.526389
6          usa       16.474324
           europe    16.425000
           japan     13.550000
3          japan     13.250000
8          usa       12.955340
Name: acceleration, dtype: float64

<br>

## Task 6 - Tampilkan jumlah mobil tiap cylinder

In [45]:
# Your code here
df.groupby(["cylinders"])["name"].count()

cylinders
3      4
4    204
5      3
6     84
8    103
Name: name, dtype: int64

<br>

## Task 7 - Tampilkan mobil dari japan dengan nilai mpg paling tinggi

In [54]:
# Your code here
car_japan = df[df["origin"] == "japan"]
car_japan.sort_values("mpg", ascending=False, inplace=False)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
324,40.8,4,85.0,65.0,2110,19.2,80,japan,datsun 210
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
...,...,...,...,...,...,...,...,...,...
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
71,19.0,3,70.0,97.0,2330,13.5,72,japan,mazda rx2 coupe
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
111,18.0,3,70.0,90.0,2124,13.5,73,japan,maxda rx3

<br>

## Task 8 - Displacement adalah jumlah volume total dari seluruh cylinder. Buat kolom baru bernama 'volume_per_cylinder'.

In [55]:
# Kode
df["volume_per_cylinder"] = df["displacement"] / df["cylinders"]
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,volume_per_cylinder
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,38.375
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,43.750
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,39.750
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,38.000
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,37.750

<br>

## Task 9 - Tampilkan jumlah mobil keluaran tahun 1975

In [61]:
model_75 = df['model_year'] == 75
display(df.loc[model_75])
display(df.loc[model_75, "name"].count())

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,volume_per_cylinder
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom,37.500000
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova,41.666667
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch,41.666667
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick,41.666667
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina,50.000000
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air,43.750000
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury,39.750000
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd,43.875000
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century,38.500000
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu,41.666667
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador,43.000000
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury,37.500000
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk,38.500000
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2,32.750000
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii,37.750000
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla,24.250000
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto,35.000000
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin,38.666667
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro,35.000000
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona,33.500000
172,25.0,4,90.0,71.0,2223,16.5,75,europe,volkswagen dasher,22.500000
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710,29.750000
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto,28.500000
175,29.0,4,90.0,70.0,1937,14.0,75,europe,volkswagen rabbit,22.500000
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer,38.666667
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls,28.750000
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504,30.000000
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl,30.250000
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le,30.250000
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc,22.750000

np.int64(30)

<br>

## Task 10 - Buat kolom baru bernama 'origin_brand' berisi nama origin dan brand-nya.

Contoh:

-usa chevrolet
-usa buick
-europe vw

In [65]:
# kode
df["origin_brand"] = df["origin"] + " - " + df["name"]
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,volume_per_cylinder,origin_brand
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,38.375,usa - chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,43.750,usa - buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,39.750,usa - plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,38.000,usa - amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,37.750,usa - ford torino
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,35.000,usa - ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,24.250,europe - vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,33.750,usa - dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,30.000,usa - ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,29.750,usa - chevy s-10

<br>

## Task 11 - Tambahkan kolom baru dengan nama kpl yang merupakan konversi dari mpg menjadi kilometer per liter (1 mpg = 0.42514 kpl).

In [80]:
# kode
df["kpl"] = (df["mpg"] * 0.42514).round(2)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,volume_per_cylinder,origin_brand,kpl
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,38.375,usa - chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,43.750,usa - buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,39.750,usa - plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,38.000,usa - amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,37.750,usa - ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,35.000,usa - ford mustang gl,11.48
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,24.250,europe - vw pickup,18.71
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,33.750,usa - dodge rampage,13.60
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,30.000,usa - ford ranger,11.90
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,29.750,usa - chevy s-10,13.18

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=520e70a9-b7fd-4903-be7f-b6533a9e0dcb' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>